Document: asus-oled
Title: Debian asus-oled Manual
Author: <insert document author here>
Abstract: This manual describes what asus-oled is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/asus-oled/asus-oled.sgml.gz

Format: postscript
Files: /usr/share/doc/asus-oled/asus-oled.ps.gz

Format: text
Files: /usr/share/doc/asus-oled/asus-oled.text.gz

Format: HTML
Index: /usr/share/doc/asus-oled/html/index.html
Files: /usr/share/doc/asus-oled/html/*.html
